# Generated by Django 4.2.7 on 2025-08-15 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisHotline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('text_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('region', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('UK', 'United Kingdom'), ('AU', 'Australia'), ('INTL', 'International')], max_length=4)),
                ('available_24_7', models.BooleanField(default=True)),
                ('languages', models.JSONField(default=list, help_text='Languages supported')),
                ('specialties', models.JSONField(default=list, help_text='Special focus areas')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['region', 'name'],
            },
        ),
        migrations.AddField(
            model_name='moodentry',
            name='coping_strategies',
            field=models.TextField(blank=True, help_text='What helped or might help?'),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='emotions',
            field=models.JSONField(default=list, help_text='List of emotions felt'),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='energy_level',
            field=models.IntegerField(choices=[(1, 'Very Low Energy'), (2, 'Low Energy'), (3, 'Moderate Energy'), (4, 'High Energy'), (5, 'Very High Energy')], default=3),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='sleep_hours',
            field=models.FloatField(blank=True, help_text='Hours of sleep last night', null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='stress_level',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Excellent')], default=3, help_text='Stress level (1-5)'),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='triggers',
            field=models.TextField(blank=True, help_text='What triggered these feelings?'),
        ),
        migrations.AlterField(
            model_name='wellnessactivity',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='Rate from 1-5 stars', null=True),
        ),
        migrations.CreateModel(
            name='WellnessInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('mood_trend', 'Mood Trend Analysis'), ('sleep_pattern', 'Sleep Pattern'), ('stress_trigger', 'Stress Trigger Identification'), ('progress_milestone', 'Progress Milestone'), ('recommendation', 'Personalized Recommendation')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_points', models.JSONField(default=dict, help_text='Supporting data for the insight')),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in insight (0-1)')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('data_access', 'Data Access'), ('data_export', 'Data Export'), ('data_delete', 'Data Deletion'), ('profile_update', 'Profile Update'), ('mood_entry', 'Mood Entry Created'), ('appointment_book', 'Appointment Booked'), ('crisis_alert', 'Crisis Alert Triggered')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CrisisAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=10)),
                ('message', models.TextField()),
                ('mood_triggers', models.JSONField(default=list)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_notified', models.BooleanField(default=False)),
                ('professional_contacted', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_crisis_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
