# Generated by Django 4.2.1 on 2025-08-14 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100)),
                ('specializations', models.JSONField(default=list)),
                ('therapy_approaches', models.JSONField(default=list)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('education', models.TextField()),
                ('bio', models.TextField()),
                ('rate_per_session', models.DecimalField(decimal_places=2, max_digits=6)),
                ('accepts_insurance', models.BooleanField(default=False)),
                ('languages_spoken', models.JSONField(default=list)),
                ('availability', models.JSONField(default=dict)),
                ('age_groups', models.JSONField(default=list)),
                ('gender_preference', models.CharField(blank=True, max_length=20)),
                ('is_accepting_clients', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('specialization_score', models.FloatField(default=0.0)),
                ('approach_score', models.FloatField(default=0.0)),
                ('availability_score', models.FloatField(default=0.0)),
                ('preference_score', models.FloatField(default=0.0)),
                ('distance_score', models.FloatField(default=0.0)),
                ('price_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_scores', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'therapist')},
            },
        ),
        migrations.CreateModel(
            name='ClientPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concerns', models.JSONField(default=list)),
                ('preferred_specializations', models.JSONField(default=list)),
                ('preferred_therapy_approaches', models.JSONField(default=list)),
                ('therapist_gender_preference', models.CharField(blank=True, max_length=20)),
                ('age_preference', models.CharField(blank=True, max_length=50)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100)),
                ('preferred_languages', models.JSONField(default=list)),
                ('session_frequency', models.CharField(default='weekly', max_length=50)),
                ('preferred_times', models.JSONField(default=list)),
                ('urgency', models.CharField(choices=[('low', 'Not urgent, flexible timing'), ('medium', 'Would like to start within 2 weeks'), ('high', 'Need to start within a few days'), ('crisis', 'Need immediate support')], default='medium', max_length=20)),
                ('previous_therapy_experience', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('session_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
                ('matching_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.matchingscore')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
